language: objective-c
osx_image: xcode8
env:
  global:
  - APP_NAME="SwiftOverlays"
script:
  - xcodebuild -project Example/Example.xcodeproj -scheme SwiftOverlays-example-debug -sdk iphonesimulator10.0 test
